# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :update_metadata do
    supply(
      track: "production",          # Oder 'beta' / 'internal'
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_screenshots: true, # Auf false setzen, wenn du Screenshots ändern willst
      skip_upload_images: true
    )
  end

  desc "Build and upload a new version to Closed Testing (Alpha)"
  lane :deploy_alpha do
    # 1. App bauen (Erstellt das .aab)
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    # 2. Hochladen
    supply(
      track: "alpha",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,    # Setz auf false, wenn du auch Texte ändern willst
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end
